### ISSUE TITLE
Redireted back to login page after successful login in idp (keycloak)

### ISSUE THREAD

**Issue by mbkh68** [temporalio/ui#1008]
**Describe the bug**
Deployed web UI to kubernetes using helm chart, sso login configured to use keycloak. when try to login, redirected to keycloak, login successfully there, when returning back, facing login page again. 

**Expected behavior**
When redirecting back from idp, should presented with working workflow UI, not being asked for login again.

**Additional context**
No log on container, no console error in browser, no failed network call in chrome developer console.

**Comment by kkcmadhu** [comment]
i see  **message | "No id_token field in oauth2 token."** in broweser. used to work fine in old ui and previous version of new ui too.

**Comment by udoniyor** [comment]
I had the same issue when using the helm chart to deploy, and when I upgraded to the latest build of the UI. The issue stems from the token sent back from the idp doesn't contain the relevant field. That hints at scope of the request being set incorrectly. I looked into the container and noticed the value for the scope is empty, I assume at some point there was a default value, which now is not set or there is an issue how it is set. 

I got around it by adding the scope as ENV:
```
    - name: TEMPORAL_AUTH_SCOPES
      value: "openid profile email"
```

**Comment by getarun** [comment]
Which is not documented in the documentation [here](https://docs.temporal.io/references/web-ui-environment-variables#temporal_auth_enabled)

**Comment by ChuckChen123** [comment]
> I had the same issue when using the helm chart to deploy, and when I upgraded to the latest build of the UI. The issue stems from the token sent back from the idp doesn't contain the relevant field. That hints at scope of the request being set incorrectly. I looked into the container and noticed the value for the scope is empty, I assume at some point there was a default value, which now is not set or there is an issue how it is set.
> 
> I got around it by adding the scope as ENV:
> 
> ```
>     - name: TEMPORAL_AUTH_SCOPES
>       value: "openid profile email"
> ```

非常感谢，我在docker配置文件中加入了- TEMPORAL_AUTH_SCOPES="openid profile email"环境变量，在sso认证的时候跳转地址加上了scope这个参数，但是在文档中并没有这个环境变量。

**Comment by ElanHasson** [comment]
How are you configuring the other values?

I get a `502 bad gateway` after a successful login in keycloak..
![image](https://github.com/temporalio/ui/assets/234704/48f6a3ef-4b34-43f4-857b-c8f56a0e9277)

No errors in the log either.

```yaml
                    - name: TEMPORAL_AUTH_ENABLED
                      value: 'true'
                    - name: TEMPORAL_AUTH_PROVIDER_URL
                      value: https://idp.local/realms/enterprise
                    - name: TEMPORAL_AUTH_ISSUER_URL
                      value: https://idp.local/realms/enterprise
                    - name: TEMPORAL_AUTH_CLIENT_ID
                      value: temporal-ui
                    - name: TEMPORAL_AUTH_CLIENT_SECRET
                      value: redacted
                    - name: TEMPORAL_AUTH_CALLBACK_URL
                      value: >-
                        https://temporal.admin.infinityflow.dev/auth/sso/callback
                    - name: TEMPORAL_AUTH_SCOPES
                      value: openid email profile
```
