### ISSUE TITLE
TEMPORAL_UI_PUBLIC_PATH not working on version 2.29.2

### ISSUE THREAD

**Issue by Kevin-sa** [temporalio/ui#2223]
When I visited several documents and did not find a solution, for example
- https://github.com/temporalio/ui/issues/2095
- https://github.com/temporalio/ui/pull/2103

## Describe the bug

When setting TEMPORAL_UI_PUBLIC_PATH to a custom path, like /temporal per the documentation [here](https://docs.temporal.io/references/web-ui-environment-variables#temporal_ui_public_path), I cannot access the UI from somedomain.com/temporal

## To Reproduce

Set TEMPORAL_UI_PUBLIC_PATH to a custom path, like /temporal
Port-forward to the temporal-web service, and go to http://localhost/:/temporal
Expected behavior

When setting TEMPORAL_UI_PUBLIC_PATH to a custom path, like /temporal per the documentation [here](https://docs.temporal.io/references/web-ui-environment-variables#temporal_ui_public_path), I can access the UI from somedomain.com/temporal

## Screenshots
```/temporal/namespaces/default/workflows```
![A](https://github.com/user-attachments/assets/0b40baa4-608a-486f-8001-c63f1f2140a5)

```/namespaces/default/workflows```
![B](https://github.com/user-attachments/assets/53472565-d4f7-4d0b-bd6c-912b6f2ce7a6)

```
  temporal-ui:
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
      #- TEMPORAL_UI_PUBLIC_PATH=temporal
    image: temporalio/ui:${TEMPORAL_UI_VERSION}
    networks:
      - temporal-network
    ports:
      - 8080:8080
```
