### ISSUE TITLE
404 Error when using Auth

### ISSUE THREAD

**Issue by keu** [temporalio/ui#2584]
**Describe the bug**
I'm running temporal UI as a docker container. I've configured it to use Clerk as Auth provider.
Unfortunately right after starting the web server crashes with 404 error.

**To Reproduce**

1. start the container with env variables set
2. see it crashed

```
2025/03/05 14:26:29 Loading config; env=docker,configDir=config
2025/03/05 14:26:29 Loading config files=[config/docker.yaml]
2025/03/05 14:26:29 Loading config; env=docker,configDir=config
2025/03/05 14:26:29 Loading config files=[config/docker.yaml]
2025/03/05 14:26:30 404 Not Found: 404 page not found
```

**Expected behavior**
--

**Screenshots**

**Desktop (please complete the following information):**

- OS: OS X
- Browser chrome
- Version 2.36.0

**Additional context**
config/docker.yaml
```
temporalGrpcAddress: localhost:7233
port: 8233
publicPath:
enableUi: true
bannerText:
cloudUi: false
defaultNamespace: default
feedbackUrl:
notifyOnNewVersion: true
refreshInterval: 0s
showTemporalSystemNamespace:
  false
disableWriteActions: false
workflowTerminateDisabled: false
workflowCancelDisabled: false
workflowSignalDisabled: false
workflowUpdateDisabled: false
workflowResetDisabled: false
batchActionsDisabled: false
startWorkflowDisabled: false
hideWorkflowQueryErrors: false
refreshWorkflowCountsDisabled: false
cors:
  cookieInsecure: true
  allowOrigins:
    # override framework's default that allows all origins "*"
    - localhost
tls:
  caFile:
  certFile:
  keyFile:
  caData:
  certData:
  keyData:
  enableHostVerification: false
  serverName:
auth:
  enabled: true
  providers:
  - label: sso
    type: oidc
    providerUrl: https://AAAAAAAA.accounts.dev/.well-known/openid-configuration
    issuerUrl:
    clientId: XXXXXXXXXX
    clientSecret: XXXXXXXXXXXX
    callbackUrl: http://localhost:8233/auth/sso/callback
    scopes:
      - openid
      - email
      - profile
codec:
  endpoint:
  passAccessToken: false
  includeCredentials: false

forwardHeaders:
  - Authorization
  - Cookie
  - X-Csrf-Token

hideLogs: false
```

logs:
```
/home/ui-server # ./start-ui-server.sh
2025/03/05 14:26:29 Loading config; env=docker,configDir=config
2025/03/05 14:26:29 Loading config files=[config/docker.yaml]
2025/03/05 14:26:29 Loading config; env=docker,configDir=config
2025/03/05 14:26:29 Loading config files=[config/docker.yaml]
2025/03/05 14:26:30 404 Not Found: 404 page not found
```

**Comment by baduker** [comment]
I have a similar issue with dex + temporal. The web UI just doesn't handle this well and probably is broken.

**Comment by baduker** [comment]
@keu did you manage to fix the issue with Clerk?

**Comment by geckiss** [comment]
We started seeing similar issue with Temporalio UI in kubernetes for version 2.38 and higher. Temporal SSO works correctly with v2.37.

**To Reproduce**
Steps to reproduce the behavior:

1. configure SSO through OIDC
```yaml
web:
  config:
    auth:
      enabled: true
      providers:
      - label: Auth0 oidc
        type: oidc
        providerUrl: https://keycloak.domain/realms/my-realm
        clientId: temporalio
        clientSecret: changeme123
        scopes:
          - openid
          - profile
          - email
        callbackUrl: https://my.domain/auth/sso/callback
        passIdToken: true
```
3. start the container `temporalio/ui:2.38.0`
4. try to enter domain  - returns `https://my.domain/login?returnUrl=https%3A%2F%2Fmy.domain%2F&error=Request+unauthorized.`

<img width="780" height="593" alt="Image" src="https://github.com/user-attachments/assets/f821fadf-84c8-489a-90f4-0dce3e04aef3" />


**Desktop (please complete the following information):**

    OS: OS X
    Browser chrome
    Version 2.36.0

**Additional context:**
Logs:

`{"time":"2025-08-01T11:18:44.57340888Z","id":"78f60d8041a0f91cf427d0a8036b39da","remote_ip":"100.67.161.3","host":"my.domain","method":"GET","uri":"/login?returnUrl=https%3A%2F%2Fmy.domain%2F&error=Request+unauthorized.","user_agent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:141.0) Gecko/20100101 Firefox/141.0","status":200,"error":"","latency":576832,"latency_human":"576.832µs","bytes_in":0,"bytes_out":1992}`
